export const ACTIONS = {
  OPEN_DRAWER: "OPEN_DRAWER",
  CLOSE_DRAWER: "CLOSE_DRAWER",
  VALIDATE_PHONE_START: "VALIDATE_PHONE_START",
  VALIDATE_PHONE_SUCCESS: "VALIDATE_PHONE_SUCCESS",
  VALIDATE_PHONE_FAILURE: "VALIDATE_PHONE_FAILURE"
};
