export const ACTIONS = {
  OPEN_DRAWER: "OPEN_DRAWER",
  CLOSE_DRAWER: "CLOSE_DRAWER",
  VALIDATE_PHONE_START: "VALIDATE_PHONE_START",
  VALIDATE_PHONE_SUCCESS: "VALIDATE_PHONE_SUCCESS",
  VALIDATE_PHONE_FAILURE: "VALIDATE_PHONE_FAILURE",
  VALIDATE_TOKEN_START: "VALIDATE_TOKEN_START",
  VALIDATE_TOKEN_SUCCESS: "VALIDATE_TOKEN_SUCCESS",
  VALIDATE_TOKEN_FAILURE: "VALIDATE_TOKEN_FAILURE",
  SAVE_PHONE_TO_STATE: "SAVE_PHONE_TO_STATE",
  ATTENDEE_LIST_LOAD_START: "ATTENDEE_LIST_LOAD_START",
  ATTENDEE_LIST_LOAD_SUCCESS: "ATTENDEE_LIST_LOAD_SUCCESS",
  ATTENDEE_LIST_LOAD_FAILURE: "ATTENDEE_LIST_LOAD_FAILURE"
  SAVE_TOKEN_TO_STATE: "SAVE_TOKEN_TO_STATE"
};
